### ISSUE TITLE
退出登录后无法继续推送二维码

### ISSUE THREAD

**Issue by su-chang** [wechaty/puppet-whatsapp#101] opened 2022-01-26 12:05 UTC

**Comment by su-chang** [comment] 2022-01-27 05:24
whatsapp-web.js 通过puppeteer监听到 `framenavigated` 事件后会主动调用 `destroy()` 方法。

参见：https://github.com/pedroslopez/whatsapp-web.js/blob/4e6a00dffee957074528543aac89d27efc9e825b/src/Client.js#L433-L438

可能需要重新init来获取新的二维码。

**Comment by lijiarui** [comment] 2022-01-27 11:11
应该不只是不推送二维码，而是退出进程。

**Comment by su-chang** [comment] 2022-02-07 13:32
@guo40020 可以把你针对whatsapp-web中退出登录后支持获取二维码的相关内容关联在这里。

**Comment by guo40020** [comment] 2022-02-08 03:29
[prevent exiting after disconnect](https://github.com/juzibot/whatsapp-web.js/commit/e0d7aee8c7426784be3ad81b8da231ce069a25ec)  
This commit modified the `destroy()` function of `whatsapp-web.js` to pervent the default behavior of terminating the browser and re-init.

**Comment by guo40020** [comment] 2022-02-08 08:29
The browser instance cannot be reused since it caused the new page to be blank or reload infinitely. Therefore, the browser will be re-instancitate after a completed session to get a clean and brand new browser env.

**Comment by guo40020** [comment] 2022-02-08 08:44
`@juzi.bot/whatsapp-web.js@1.15.10` provides the new solution stated above, which is tested on my machine with the bug resolved.  
Close this issue once resolved is confirmed plz. @su-chang

**Comment by guo40020** [comment] 2022-02-09 12:58
[related commit](https://github.com/juzibot/whatsapp-web.js/commit/87efc73e1c1c35cbeed56d66a5d75585d0fe2b00) fixed

**Closed by guo40020** 2022-02-09 12:58 UTC
